### ISSUE TITLE
Shorten tags please

### ISSUE THREAD

**Issue by v-karbovnichy** [structurizr/themes#2]
I suggest to shorten the tags used in themes according to the following:
* `Amazon Web Services - Something` -> `AWS Something`
* `Microsoft Azure - Something` -> `Azure Something`
* `Google Cloud Platform - Something` - > `GCP Something`

Check your filenames for icons - it's already shortened there. 
It's basically unpractical to have so long tags to achieve the proper icons in target model.

**Comment by simonbrowndotje** [comment]
These themes are already in use by people, so changing them would break their workspaces. Since the themes are open source, feel free to create your own version with different tags, or perhaps just a subset of the styles.
