### ISSUE TITLE
How to apply theme?

### ISSUE THREAD

**Issue by v-karbovnichy** [structurizr/themes#3]
I have a problem with applying the existing theme to my C4 model.
What I did to apply theme to my workspace is:
* download json from this repo
* convert it to yaml via free online service (I need this because we have yaml C4 models stored in git in our company, ymmv)
* crop all outside of `elements` array
* add 6 spaces to all lines
* add the resulting text in my yaml file
* upload yaml back to structurizr

I wish it could be easier, like just an `Apply` button on the theme browser page, or `Import theme` button somewhere in my workspace editor. Maybe I just didn't find it? 🙈 

Also I would like to import not everything from the theme, but only some items.

Another idea: in workspace editor, in the styles section, you could probably show all the themes from this repo in some dropdown, for people to instantly be able to import those in their workspaces. I actually did the creation of the Azure icons (not all though) by going exactly the way you did, only to find this repo a month after.

**Comment by simonbrowndotje** [comment]
If you're using Structurizr to render diagrams, you can set one or more themes on a workspaces as follows:

- Workspace editor: there's a setting under "Configuration" (e.g. https://structurizr.com/demo#configuration)
- DSL: Set the `themes` property (e.g. https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#themes)
- Code: Most of the Structurizr client libraries allow you to set a theme (e.g. https://github.com/structurizr/java/blob/master/structurizr-core/src/com/structurizr/view/Configuration.java#L70)

To use a subset of any theme, I'd recommending forking it and creating your own customised version.

Hope that helps.

**Comment by v-karbovnichy** [comment]
Yes, Simon, it seems i just didn't pay enough attention to those theming features.

I found this UI just now:
![image](https://user-images.githubusercontent.com/7301634/87979317-ef093880-cae2-11ea-9380-705e641cf8bf.png)
