### ISSUE TITLE
Which tool did you use to convert the Azure SVGs into PNG

### ISSUE THREAD

**Issue by phatcher** [structurizr/themes#8]
There's a new set of Azure icons as of Jan 2023, I can do a PR but want to keep the images stable compared to the prior ones so would like to know how they were converted.

Can just do it using the tech we used for the PlantUml icons if that's good enough

**Comment by simonbrowndotje** [comment]
I have theme creation scripted (it's more than just converting the SVGs), so I've added the new Azure theme for you -> https://structurizr.com/help/theme?url=https://static.structurizr.com/themes/microsoft-azure-2023.01.24/theme.json

**Comment by phatcher** [comment]
Simon, thanks for that
